parameters:
    database_driver:   pdo_mysql
    database_host:     %database.host%
    database_port:     %database.port%
    database_name:     %database.name%
    database_user:     %database.user%
    database_password: %database.password%

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            123lk4j231l4k2h3
